CREATE TABLE IF NOT EXISTS MAIL_LOGIN_SESSION (
    JTI VARCHAR(64) NOT NULL PRIMARY KEY,
    USER_ID VARCHAR(128) NOT NULL,
    DOMAIN VARCHAR(128) NOT NULL,
    CLIENT_IP VARCHAR(64),
    USER_AGENT VARCHAR(256),
    DEVICE_NAME VARCHAR(128),
    LOGIN_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    LAST_ACCESS DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_user_domain (USER_ID, DOMAIN)
);

CREATE TABLE IF NOT EXISTS MAIL_LOGIN_HISTORY (
    SEQ INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR(128) NOT NULL,
    DOMAIN VARCHAR(128) NOT NULL,
    JTI VARCHAR(64),
    CLIENT_IP VARCHAR(64),
    USER_AGENT VARCHAR(256),
    LOGIN_TIME DATETIME DEFAULT CURRENT_TIMESTAMP,
    ACTION VARCHAR(20) -- 'LOGIN', 'LOGOUT', 'KICKOUT'
);

CREATE TABLE IF NOT EXISTS MAIL_USER_DEVICE (
    SEQ INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR(128) NOT NULL,
    DOMAIN VARCHAR(128) NOT NULL,
    DEVICE_NAME VARCHAR(128),
    USER_AGENT VARCHAR(256) NOT NULL,
    IS_ALLOWED BOOLEAN DEFAULT TRUE,
    REGISTER_TIME DATETIME DEFAULT CURRENT_TIMESTAMP
);
