CREATE TABLE IF NOT EXISTS MAIL_LOGIN_SESSION (
    JTI VARCHAR(255) PRIMARY KEY,
    USER_ID VARCHAR(100) NOT NULL,
    DOMAIN VARCHAR(100) NOT NULL,
    CLIENT_IP VARCHAR(50),
    USER_AGENT TEXT,
    DEVICE_NAME VARCHAR(100),
    LOGIN_TIME DATETIME,
    LAST_ACCESS DATETIME
);

CREATE TABLE IF NOT EXISTS MAIL_USER_DEVICE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR(100) NOT NULL,
    DOMAIN VARCHAR(100) NOT NULL,
    DEVICE_NAME VARCHAR(100),
    USER_AGENT TEXT,
    IS_ALLOWED TINYINT(1) DEFAULT 1,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS MAIL_LOGIN_HISTORY (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID VARCHAR(100) NOT NULL,
    DOMAIN VARCHAR(100) NOT NULL,
    JTI VARCHAR(255),
    CLIENT_IP VARCHAR(50),
    USER_AGENT TEXT,
    LOGIN_TIME DATETIME,
    ACTION VARCHAR(50)
);
